### ISSUE TITLE
Image count goes up way too fast

### ISSUE THREAD

**Issue by typhoon71** [ccloli/E-Hentai-Downloader#49] opened 2016-10-03 21:43 UTC
I noticed the image limit gets "consumed" really fast: I downloaded a zip with 31 pics, and the counter went up from 0/5000 to 265/5000.
What is happening?

**Comment by ccloli** [comment] 2016-10-04 07:36
Hi, I've checked a [gallery](http://g.e-hentai.org/g/982701/6e826909e1/) which most pages have original image download link. With the [image limits rule](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits), it should only take `62 * (1 + 5) = 372` limits. When I started, the image limits is `85/5000`, so when I finished it should be `372 + 85 = 457`.

However, thought it doesn't finished downloading, the image limits has increased to `1065` (with 57 images succeed, 10 failed times, but doesn't request a new image URL). 

I'll checked what's up soon, please be patient. As I'm not sure if it is a bug or E-Hentai increased the image limits count (however the [update log](https://forums.e-hentai.org/index.php?s=51acc4e6d2522a30e206e9c21940f9d8&showtopic=188685) doesn't show this), I'll mark this issue as `Question` tag temporarily.

**Comment by ccloli** [comment] 2016-10-04 09:17
It seems that now E-Hentai use a flexible way to calculate image limits when downloading original images. 

From my test, before I viewed [this page](http://g.e-hentai.org/s/2e53ef7721/982809-1), my image limits was `1002`, after that it's `1003`, then I clicked download original image (1559 x 2196 485.1 KB), my limits increased to `1005` (+2). 

But when I checked the gallery in previous comment, after I viewed [the first page](http://g.e-hentai.org/s/9fdd41d577/982701-1), it's `1006`, and after I clicked download original image (2698 x 3840 3.98 MB), it increased to `1025` (+19).

All my test (image with * is NSFW): 
- [2698 x 3840 3.98 MB / 982701](http://g.e-hentai.org/s/9fdd41d577/982701-1): 19
- [1559 x 2196 485.1 KB / 982809](http://g.e-hentai.org/s/2e53ef7721/982809-1): 2
- [1559 x 2196 95.83 KB / 982809](http://g.e-hentai.org/s/5aa07f5f75/982809-2): 0
- [1559 x 2196 1.49 MB / 982809](http://g.e-hentai.org/s/99aac1065a/982809-3): 7
- [2149 x 3051 590.7 KB / 982833](http://g.e-hentai.org/s/0f2f3e5a89/982833-1): 2
- [2141 x 3042 379.2 KB / 982833](http://g.e-hentai.org/s/d2eba67695/982833-2): 1
- [2137 x 3034 712.2 KB / 982833](http://g.e-hentai.org/s/43ef04035a/982833-3): 3 *
- [2140 x 3042 857.6 KB / 982833](http://g.e-hentai.org/s/4b82245962/982833-7): 4 *
- [1722 x 2472 10.59 MB / 982748](http://g.e-hentai.org/s/e6f96a1de0/982748-1): 52
- [1613 x 2469 2.36 MB / 982748](http://g.e-hentai.org/s/e0d8d70872/982748-2): 11
- [1634 x 2476 3.36 MB / 982748](http://g.e-hentai.org/s/8a70809c51/982748-3): 16
- [1658 x 2472 3.92 MB / 982748](http://g.e-hentai.org/s/29f9458179/982748-4): 19
- [1662 x 2474 3.28 MB / 982748](http://g.e-hentai.org/s/e5f1e9c256/982748-5): 16
- [1694 x 2478 4.01 MB / 982748](http://g.e-hentai.org/s/93546a8486/982748-6): 20

So from these test, it seems that the image limits is now calculated by file size, costing 1 limit per 0.2MB (or per 200KB). So it's not a bug of E-Hentai Downloader, but E-Hentai uses a new way to calculate image limits.

I'll update the image limits wiki page soon.

**Comment by ccloli** [comment] 2016-10-04 09:57
BTW, with the new calculating ways, maybe I can pre-calculate image limits before user start downloading, so that they can know how many limits will be used.

**Comment by typhoon71** [comment] 2016-10-04 17:48
Oh, so the limit is counted based on size now, and the script shows the available points intead of the available images. Got it.
Pre-calculating would be nice, if it's possible, it would help managing the points.
Thanks for discovering what's was going on.

**Comment by ccloli** [comment] 2016-10-05 11:12
Now the feature has been added, will be released and enabled by default in next version. 

Anyway, it's just an estimated value, as I can't fetch all the pages then calculate how many limits it'll cost before downloading, it's calculated by this:
```
Page Length + File Total Size (MB) * 5
```

You can disabled it by checking _Settings -> Basic -> Disable pre-calculating image limits cost_. It'll be shown on the title of the action box, like `Estimated Limits Cost: 6258`.

![qq 20161005190104](https://cloud.githubusercontent.com/assets/8115912/19110721/2e94565e-8b2e-11e6-8633-24e53a8f11fd.png)

**Closed** 2016-10-06 14:51 UTC
Labels: enhancement, question

**Comment by typhoon71** [comment] 2016-10-06 15:42
Nice, thanks.
