### ISSUE TITLE
Response Error/Failed! (Wrong MIME)

### ISSUE THREAD

**Issue by lemou** [ccloli/E-Hentai-Downloader#59] opened 2017-01-30 19:14 UTC
Since the change to e-hentai.org when i try to download, the script fail with a "Response Error" if i'm not logged and "Failed! (Wrong MIME)" if i'm logged. I don't know because of that update or it happen only just me. so please check. Thank you.
And i use Chrome with violent monkey.

**Comment by cheon7886** [comment] 2017-02-04 07:28
Hello. It happened to me, too.
I used pptp vpn server, chrome with tapermonkey.

**Comment by ccloli** [comment] 2017-02-04 15:52
Sorry but I'm not sure how it happens, maybe the reason is the cookie doesn't keep in sync with e-hentai.org. 

Try logging out your E-Hentai account and logging in again. If it still doesn't work, please try visiting any page of any gallery, then click the link `Download original **** x **** **** MB source` at the bottom of the page, it should redirect you to the login page and just login, if the link doesn't exist, switch to another page or try another gallery. That should fixes the problem.

If you still have the problem and that download source link really gives you the original image, please reply me the link of problem gallery, and press F12, switch to `Console`, copy all the logs that started with `[EHD]` and paste them here, thank you.

**Comment by iShyboy** [comment] 2017-02-06 10:42
I had this error at the time EXH got down this weekend, but it got normal after I cleared my cookies and setup my account and settings again.

**Comment by Akiteru2912** [comment] 2017-02-10 03:42
i have the same error until now. all image download succeed, zip succeed, but failed to download. try to clear all and retry but it not help :/
![untitled](https://cloud.githubusercontent.com/assets/19964080/22813357/9b1db30c-ef7d-11e6-8aaf-e687ff60710e.png)
`

**Comment by ccloli** [comment] 2017-02-10 03:55
@Akiteru2912 See https://github.com/ccloli/E-Hentai-Downloader/wiki/Can't-make-Zip-file-successfully , that means you don't have free memory or the file is too large. Try enabling File System on Settings or using Pages Range.

**Comment by Akiteru2912** [comment] 2017-02-10 06:45
thank you so much, i used file system and it's work. sorry for my lack of observed :D

**Comment by lemou** [comment] 2017-02-11 20:53
it works thanks, but when i try without being logged, the script still fail with a "Response Error"

if you want to check, for example with the gallery:
https://e-hentai.org/g/1028293/0214846a9d/
the console log:
http://pastebin.com/s0aDsGPD

**Comment by ccloli** [comment] 2017-02-12 08:43
Maybe the regex rule of image url for not login user isn't correct. I also tried the gallery, but it downloaded successfully. For me, the source code of the gallery viewing page has a specific id `id="img"` so that the script can get the correct url. But from your console log, the script used the last regex rule which for pages that don't have `id="img"` then it threw the errors.

Please help me to copy and paste the source code from your side, just logout and confirm that you can still reproduce the bug, then open the following link on your Chrome: `view-source:https://e-hentai.org/s/0f244ec219/1028293-3`. If the link can't be opened, open any gallery and then click any page/thumbnail, right click anywhere and select `View page source`.

**Comment by lemou** [comment] 2017-02-15 20:32
I can still reproduce the bug.
The source code:
http://pastebin.com/7FEd8JWM

**Comment by ccloli** [comment] 2017-02-17 14:09
Fixed in 1.25.

**Closed by ccloli** 2017-02-17 14:09 UTC
Labels: bug
